// Auto-generated: Counter enum with Display and try_from_str implementations.
// Source: MTG Wiki — Counter (marker) / Full List
// Note: keep `super::Terminal` in scope where you include this file.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Counter {
    PlusOnePlusOne,
    MinusOneMinusOne,
    PlusZeroPlusOne,
    PlusZeroPlusTwo,
    PlusOnePlusZero,
    PlusOnePlusTwo,
    PlusTwoPlusZero,
    PlusTwoPlusTwo,
    MinusZeroMinusOne,
    MinusZeroMinusTwo,
    MinusOneMinusZero,
    MinusTwoMinusOne,
    MinusTwoMinusTwo,
    Charge,
    Defense,
    Energy,
    Finality,
    Lore,
    Loyalty,
    Oil,
    Poison,
    Stun,
    Time,
    Deathtouch,
    DoubleStrike,
    FirstStrike,
    Flying,
    Haste,
    Hexproof,
    Indestructible,
    Lifelink,
    Menace,
    Reach,
    Shadow,
    Trample,
    Vigilance,
    Age,
    Crank,
    Divinity,
    Fade,
    Ki,
    Level,
    Rad,
    Shield,
    Spore,
    Ticket,
    Brick,
    Depletion,
    Experience,
    Quest,
    Storage,
    Verse,
    Acorn,
    Aim,
    Blaze,
    Blood,
    Bounty,
    Coin,
    Collection,
    Corpse,
    Delay,
    Devotion,
    Doom,
    Dream,
    Egg,
    Eon,
    Fate,
    Feather,
    Fetch,
    Flame,
    Flood,
    Fungus,
    Fuse,
    Gold,
    Growth,
    Hatchling,
    Healing,
    Hit,
    Hour,
    Ice,
    Infection,
    Judgment,
    Landmark,
    Luck,
    Net,
    Omen,
    Page,
    Plague,
    Point,
    Pressure,
    Prey,
    Pupa,
    Polyp,
    Scream,
    Scroll,
    Slime,
    Soul,
    Spark,
    Spite,
    Stash,
    Story,
    Strife,
    Study,
    Supply,
    Suspect,
    Takeover,
    Task,
    Theft,
    Tide,
    Tower,
    Training,
    Trap,
    Treasure,
    Unity,
    Unlock,
    Valor,
    Velocity,
    Vow,
    Voyage,
    Wage,
    Winch,
    Wind,
    Wish,
    Aegis,
    Arrow,
    Arrowhead,
    Awakening,
    Bait,
    Blessing,
    Blight,
    Bloodline,
    Bloodstain,
    Book,
    Bore,
    Brain,
    Bribery,
    Burden,
    Cage,
    Carrion,
    Chip,
    Chorus,
    Contested,
    Credit,
    Croak,
    Crystal,
    Cube,
    Component,
    Corruption,
    Currency,
    Death,
    Descent,
    Despair,
    Discovery,
    Dread,
    Duty,
    Echo,
    Elixir,
    Ember,
    Enlightened,
    Eruption,
    Everything,
    Eyeball,
    Eyestalk,
    Feeding,
    Fellowship,
    Filibuster,
    Foreshadow,
    Funk,
    Fury,
    Gem,
    Ghostform,
    Globe,
    Glyph,
    Hack,
    Harmony,
    Hatching,
    Hone,
    Hoofprint,
    Hope,
    Hourglass,
    Hunger,
    Husk,
    Impostor,
    Incarnation,
    Incubation,
    Influence,
    Ingenuity,
    Intel,
    Intervention,
    Isolation,
    Invitation,
    Javelin,
    Kick,
    Knickknack,
    Knowledge,
    Loot,
    Magnet,
    Manifestation,
    Mannequin,
    Matrix,
    Memory,
    Midway,
    Mine,
    Mining,
    Mire,
    Music,
    Muster,
    Necrodermis,
    Nest,
    Night,
    Ore,
    Pain,
    Palliation,
    Paralyzation,
    Pause,
    Petal,
    Petrification,
    Phyresis,
    Phylactery,
    Pin,
    Plot,
    Pop,
    Possession,
    Rejection,
    Reprieve,
    Rev,
    Revival,
    Ribbon,
    Ritual,
    Rope,
    Rust,
    Shell,
    Shoe,
    Shred,
    Skewer,
    Silver,
    Sleep,
    Sleight,
    Slumber,
    Soot,
    ThirdDegreeBurn,
    Vitality,
    Vortex,
    Void,
    Volatile,
}

impl std::fmt::Display for Counter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Counter::PlusOnePlusOne => write!(f, "+1/+1 counter"),
            Counter::MinusOneMinusOne => write!(f, "-1/-1 counter"),
            Counter::PlusZeroPlusOne => write!(f, "+0/+1 counter"),
            Counter::PlusZeroPlusTwo => write!(f, "+0/+2 counter"),
            Counter::PlusOnePlusZero => write!(f, "+1/+0 counter"),
            Counter::PlusOnePlusTwo => write!(f, "+1/+2 counter"),
            Counter::PlusTwoPlusZero => write!(f, "+2/+0 counter"),
            Counter::PlusTwoPlusTwo => write!(f, "+2/+2 counter"),
            Counter::MinusZeroMinusOne => write!(f, "-0/-1 counter"),
            Counter::MinusZeroMinusTwo => write!(f, "-0/-2 counter"),
            Counter::MinusOneMinusZero => write!(f, "-1/-0 counter"),
            Counter::MinusTwoMinusOne => write!(f, "-2/-1 counter"),
            Counter::MinusTwoMinusTwo => write!(f, "-2/-2 counter"),
            Counter::Charge => write!(f, "charge counter"),
            Counter::Defense => write!(f, "defense counter"),
            Counter::Energy => write!(f, "energy counter"),
            Counter::Finality => write!(f, "finality counter"),
            Counter::Lore => write!(f, "lore counter"),
            Counter::Loyalty => write!(f, "loyalty counter"),
            Counter::Oil => write!(f, "oil counter"),
            Counter::Poison => write!(f, "poison counter"),
            Counter::Stun => write!(f, "stun counter"),
            Counter::Time => write!(f, "time counter"),
            Counter::Deathtouch => write!(f, "deathtouch counter"),
            Counter::DoubleStrike => write!(f, "double strike counter"),
            Counter::FirstStrike => write!(f, "first strike counter"),
            Counter::Flying => write!(f, "flying counter"),
            Counter::Haste => write!(f, "haste counter"),
            Counter::Hexproof => write!(f, "hexproof counter"),
            Counter::Indestructible => write!(f, "indestructible counter"),
            Counter::Lifelink => write!(f, "lifelink counter"),
            Counter::Menace => write!(f, "menace counter"),
            Counter::Reach => write!(f, "reach counter"),
            Counter::Shadow => write!(f, "shadow counter"),
            Counter::Trample => write!(f, "trample counter"),
            Counter::Vigilance => write!(f, "vigilance counter"),
            Counter::Age => write!(f, "age counter"),
            Counter::Crank => write!(f, "crank counter"),
            Counter::Divinity => write!(f, "divinity counter"),
            Counter::Fade => write!(f, "fade counter"),
            Counter::Ki => write!(f, "ki counter"),
            Counter::Level => write!(f, "level counter"),
            Counter::Rad => write!(f, "rad counter"),
            Counter::Shield => write!(f, "shield counter"),
            Counter::Spore => write!(f, "spore counter"),
            Counter::Ticket => write!(f, "ticket counter"),
            Counter::Brick => write!(f, "brick counter"),
            Counter::Depletion => write!(f, "depletion counter"),
            Counter::Experience => write!(f, "experience counter"),
            Counter::Quest => write!(f, "quest counter"),
            Counter::Storage => write!(f, "storage counter"),
            Counter::Verse => write!(f, "verse counter"),
            Counter::Acorn => write!(f, "acorn counter"),
            Counter::Aim => write!(f, "aim counter"),
            Counter::Blaze => write!(f, "blaze counter"),
            Counter::Blood => write!(f, "blood counter"),
            Counter::Bounty => write!(f, "bounty counter"),
            Counter::Coin => write!(f, "coin counter"),
            Counter::Collection => write!(f, "collection counter"),
            Counter::Corpse => write!(f, "corpse counter"),
            Counter::Delay => write!(f, "delay counter"),
            Counter::Devotion => write!(f, "devotion counter"),
            Counter::Doom => write!(f, "doom counter"),
            Counter::Dream => write!(f, "dream counter"),
            Counter::Egg => write!(f, "egg counter"),
            Counter::Eon => write!(f, "eon counter"),
            Counter::Fate => write!(f, "fate counter"),
            Counter::Feather => write!(f, "feather counter"),
            Counter::Fetch => write!(f, "fetch counter"),
            Counter::Flame => write!(f, "flame counter"),
            Counter::Flood => write!(f, "flood counter"),
            Counter::Fungus => write!(f, "fungus counter"),
            Counter::Fuse => write!(f, "fuse counter"),
            Counter::Gold => write!(f, "gold counter"),
            Counter::Growth => write!(f, "growth counter"),
            Counter::Hatchling => write!(f, "hatchling counter"),
            Counter::Healing => write!(f, "healing counter"),
            Counter::Hit => write!(f, "hit counter"),
            Counter::Hour => write!(f, "hour counter"),
            Counter::Ice => write!(f, "ice counter"),
            Counter::Infection => write!(f, "infection counter"),
            Counter::Judgment => write!(f, "judgment counter"),
            Counter::Landmark => write!(f, "landmark counter"),
            Counter::Luck => write!(f, "luck counter"),
            Counter::Net => write!(f, "net counter"),
            Counter::Omen => write!(f, "omen counter"),
            Counter::Page => write!(f, "page counter"),
            Counter::Plague => write!(f, "plague counter"),
            Counter::Point => write!(f, "point counter"),
            Counter::Pressure => write!(f, "pressure counter"),
            Counter::Prey => write!(f, "prey counter"),
            Counter::Pupa => write!(f, "pupa counter"),
            Counter::Polyp => write!(f, "polyp counter"),
            Counter::Scream => write!(f, "scream counter"),
            Counter::Scroll => write!(f, "scroll counter"),
            Counter::Slime => write!(f, "slime counter"),
            Counter::Soul => write!(f, "soul counter"),
            Counter::Spark => write!(f, "spark counter"),
            Counter::Spite => write!(f, "spite counter"),
            Counter::Stash => write!(f, "stash counter"),
            Counter::Story => write!(f, "story counter"),
            Counter::Strife => write!(f, "strife counter"),
            Counter::Study => write!(f, "study counter"),
            Counter::Supply => write!(f, "supply counter"),
            Counter::Suspect => write!(f, "suspect counter"),
            Counter::Takeover => write!(f, "takeover counter"),
            Counter::Task => write!(f, "task counter"),
            Counter::Theft => write!(f, "theft counter"),
            Counter::Tide => write!(f, "tide counter"),
            Counter::Tower => write!(f, "tower counter"),
            Counter::Training => write!(f, "training counter"),
            Counter::Trap => write!(f, "trap counter"),
            Counter::Treasure => write!(f, "treasure counter"),
            Counter::Unity => write!(f, "unity counter"),
            Counter::Unlock => write!(f, "unlock counter"),
            Counter::Valor => write!(f, "valor counter"),
            Counter::Velocity => write!(f, "velocity counter"),
            Counter::Vow => write!(f, "vow counter"),
            Counter::Voyage => write!(f, "voyage counter"),
            Counter::Wage => write!(f, "wage counter"),
            Counter::Winch => write!(f, "winch counter"),
            Counter::Wind => write!(f, "wind counter"),
            Counter::Wish => write!(f, "wish counter"),
            Counter::Aegis => write!(f, "aegis counter"),
            Counter::Arrow => write!(f, "arrow counter"),
            Counter::Arrowhead => write!(f, "arrowhead counter"),
            Counter::Awakening => write!(f, "awakening counter"),
            Counter::Bait => write!(f, "bait counter"),
            Counter::Blessing => write!(f, "blessing counter"),
            Counter::Blight => write!(f, "blight counter"),
            Counter::Bloodline => write!(f, "bloodline counter"),
            Counter::Bloodstain => write!(f, "bloodstain counter"),
            Counter::Book => write!(f, "book counter"),
            Counter::Bore => write!(f, "bore counter"),
            Counter::Brain => write!(f, "brain counter"),
            Counter::Bribery => write!(f, "bribery counter"),
            Counter::Burden => write!(f, "burden counter"),
            Counter::Cage => write!(f, "cage counter"),
            Counter::Carrion => write!(f, "carrion counter"),
            Counter::Chip => write!(f, "chip counter"),
            Counter::Chorus => write!(f, "chorus counter"),
            Counter::Contested => write!(f, "contested counter"),
            Counter::Credit => write!(f, "credit counter"),
            Counter::Croak => write!(f, "croak counter"),
            Counter::Crystal => write!(f, "crystal counter"),
            Counter::Cube => write!(f, "cube counter"),
            Counter::Component => write!(f, "component counter"),
            Counter::Corruption => write!(f, "corruption counter"),
            Counter::Currency => write!(f, "currency counter"),
            Counter::Death => write!(f, "death counter"),
            Counter::Descent => write!(f, "descent counter"),
            Counter::Despair => write!(f, "despair counter"),
            Counter::Discovery => write!(f, "discovery counter"),
            Counter::Dread => write!(f, "dread counter"),
            Counter::Duty => write!(f, "duty counter"),
            Counter::Echo => write!(f, "echo counter"),
            Counter::Elixir => write!(f, "elixir counter"),
            Counter::Ember => write!(f, "ember counter"),
            Counter::Enlightened => write!(f, "enlightened counter"),
            Counter::Eruption => write!(f, "eruption counter"),
            Counter::Everything => write!(f, "everything counter"),
            Counter::Eyeball => write!(f, "eyeball counter"),
            Counter::Eyestalk => write!(f, "eyestalk counter"),
            Counter::Feeding => write!(f, "feeding counter"),
            Counter::Fellowship => write!(f, "fellowship counter"),
            Counter::Filibuster => write!(f, "filibuster counter"),
            Counter::Foreshadow => write!(f, "foreshadow counter"),
            Counter::Funk => write!(f, "funk counter"),
            Counter::Fury => write!(f, "fury counter"),
            Counter::Gem => write!(f, "gem counter"),
            Counter::Ghostform => write!(f, "ghostform counter"),
            Counter::Globe => write!(f, "globe counter"),
            Counter::Glyph => write!(f, "glyph counter"),
            Counter::Hack => write!(f, "hack counter"),
            Counter::Harmony => write!(f, "harmony counter"),
            Counter::Hatching => write!(f, "hatching counter"),
            Counter::Hone => write!(f, "hone counter"),
            Counter::Hoofprint => write!(f, "hoofprint counter"),
            Counter::Hope => write!(f, "hope counter"),
            Counter::Hourglass => write!(f, "hourglass counter"),
            Counter::Hunger => write!(f, "hunger counter"),
            Counter::Husk => write!(f, "husk counter"),
            Counter::Impostor => write!(f, "impostor counter"),
            Counter::Incarnation => write!(f, "incarnation counter"),
            Counter::Incubation => write!(f, "incubation counter"),
            Counter::Influence => write!(f, "influence counter"),
            Counter::Ingenuity => write!(f, "ingenuity counter"),
            Counter::Intel => write!(f, "intel counter"),
            Counter::Intervention => write!(f, "intervention counter"),
            Counter::Isolation => write!(f, "isolation counter"),
            Counter::Invitation => write!(f, "invitation counter"),
            Counter::Javelin => write!(f, "javelin counter"),
            Counter::Kick => write!(f, "kick counter"),
            Counter::Knickknack => write!(f, "knickknack counter"),
            Counter::Knowledge => write!(f, "knowledge counter"),
            Counter::Loot => write!(f, "loot counter"),
            Counter::Magnet => write!(f, "magnet counter"),
            Counter::Manifestation => write!(f, "manifestation counter"),
            Counter::Mannequin => write!(f, "mannequin counter"),
            Counter::Matrix => write!(f, "matrix counter"),
            Counter::Memory => write!(f, "memory counter"),
            Counter::Midway => write!(f, "midway counter"),
            Counter::Mine => write!(f, "mine counter"),
            Counter::Mining => write!(f, "mining counter"),
            Counter::Mire => write!(f, "mire counter"),
            Counter::Music => write!(f, "music counter"),
            Counter::Muster => write!(f, "muster counter"),
            Counter::Necrodermis => write!(f, "necrodermis counter"),
            Counter::Nest => write!(f, "nest counter"),
            Counter::Night => write!(f, "night counter"),
            Counter::Ore => write!(f, "ore counter"),
            Counter::Pain => write!(f, "pain counter"),
            Counter::Palliation => write!(f, "palliation counter"),
            Counter::Paralyzation => write!(f, "paralyzation counter"),
            Counter::Pause => write!(f, "pause counter"),
            Counter::Petal => write!(f, "petal counter"),
            Counter::Petrification => write!(f, "petrification counter"),
            Counter::Phyresis => write!(f, "phyresis counter"),
            Counter::Phylactery => write!(f, "phylactery counter"),
            Counter::Pin => write!(f, "pin counter"),
            Counter::Plot => write!(f, "plot counter"),
            Counter::Pop => write!(f, "pop counter"),
            Counter::Possession => write!(f, "possession counter"),
            Counter::Rejection => write!(f, "rejection counter"),
            Counter::Reprieve => write!(f, "reprieve counter"),
            Counter::Rev => write!(f, "rev counter"),
            Counter::Revival => write!(f, "revival counter"),
            Counter::Ribbon => write!(f, "ribbon counter"),
            Counter::Ritual => write!(f, "ritual counter"),
            Counter::Rope => write!(f, "rope counter"),
            Counter::Rust => write!(f, "rust counter"),
            Counter::Shell => write!(f, "shell counter"),
            Counter::Shoe => write!(f, "shoe counter"),
            Counter::Shred => write!(f, "shred counter"),
            Counter::Skewer => write!(f, "skewer counter"),
            Counter::Silver => write!(f, "silver counter"),
            Counter::Sleep => write!(f, "sleep counter"),
            Counter::Sleight => write!(f, "sleight counter"),
            Counter::Slumber => write!(f, "slumber counter"),
            Counter::Soot => write!(f, "soot counter"),
            Counter::ThirdDegreeBurn => write!(f, "third-degree-burn counter"),
            Counter::Vitality => write!(f, "vitality counter"),
            Counter::Vortex => write!(f, "vortex counter"),
            Counter::Void => write!(f, "void counter"),
            Counter::Volatile => write!(f, "volatile counter"),
        }
    }
}

impl super::Terminal for Counter {
    fn try_from_str(source: &str) -> Option<Self> {
        match source {
            "+1/+1 counter" | "+1/+1 counters" => Some(Counter::PlusOnePlusOne),
            "-1/-1 counter" | "-1/-1 counters" => Some(Counter::MinusOneMinusOne),
            "+0/+1 counter" | "+0/+1 counters" => Some(Counter::PlusZeroPlusOne),
            "+0/+2 counter" | "+0/+2 counters" => Some(Counter::PlusZeroPlusTwo),
            "+1/+0 counter" | "+1/+0 counters" => Some(Counter::PlusOnePlusZero),
            "+1/+2 counter" | "+1/+2 counters" => Some(Counter::PlusOnePlusTwo),
            "+2/+0 counter" | "+2/+0 counters" => Some(Counter::PlusTwoPlusZero),
            "+2/+2 counter" | "+2/+2 counters" => Some(Counter::PlusTwoPlusTwo),
            "-0/-1 counter" | "-0/-1 counters" => Some(Counter::MinusZeroMinusOne),
            "-0/-2 counter" | "-0/-2 counters" => Some(Counter::MinusZeroMinusTwo),
            "-1/-0 counter" | "-1/-0 counters" => Some(Counter::MinusOneMinusZero),
            "-2/-1 counter" | "-2/-1 counters" => Some(Counter::MinusTwoMinusOne),
            "-2/-2 counter" | "-2/-2 counters" => Some(Counter::MinusTwoMinusTwo),
            "charge counter" | "charge counters" => Some(Counter::Charge),
            "defense counter" | "defense counters" => Some(Counter::Defense),
            "energy counter" | "energy counters" => Some(Counter::Energy),
            "finality counter" | "finality counters" => Some(Counter::Finality),
            "lore counter" | "lore counters" => Some(Counter::Lore),
            "loyalty counter" | "loyalty counters" => Some(Counter::Loyalty),
            "oil counter" | "oil counters" => Some(Counter::Oil),
            "poison counter" | "poison counters" => Some(Counter::Poison),
            "stun counter" | "stun counters" => Some(Counter::Stun),
            "time counter" | "time counters" => Some(Counter::Time),
            "deathtouch counter" | "deathtouch counters" => Some(Counter::Deathtouch),
            "double strike counter" | "double strike counters" => Some(Counter::DoubleStrike),
            "first strike counter" | "first strike counters" => Some(Counter::FirstStrike),
            "flying counter" | "flying counters" => Some(Counter::Flying),
            "haste counter" | "haste counters" => Some(Counter::Haste),
            "hexproof counter" | "hexproof counters" => Some(Counter::Hexproof),
            "indestructible counter" | "indestructible counters" => Some(Counter::Indestructible),
            "lifelink counter" | "lifelink counters" => Some(Counter::Lifelink),
            "menace counter" | "menace counters" => Some(Counter::Menace),
            "reach counter" | "reach counters" => Some(Counter::Reach),
            "shadow counter" | "shadow counters" => Some(Counter::Shadow),
            "trample counter" | "trample counters" => Some(Counter::Trample),
            "vigilance counter" | "vigilance counters" => Some(Counter::Vigilance),
            "age counter" | "age counters" => Some(Counter::Age),
            "crank counter" | "crank counters" => Some(Counter::Crank),
            "divinity counter" | "divinity counters" => Some(Counter::Divinity),
            "fade counter" | "fade counters" => Some(Counter::Fade),
            "ki counter" | "ki counters" => Some(Counter::Ki),
            "level counter" | "level counters" => Some(Counter::Level),
            "rad counter" | "rad counters" => Some(Counter::Rad),
            "shield counter" | "shield counters" => Some(Counter::Shield),
            "spore counter" | "spore counters" => Some(Counter::Spore),
            "ticket counter" | "ticket counters" => Some(Counter::Ticket),
            "brick counter" | "brick counters" => Some(Counter::Brick),
            "depletion counter" | "depletion counters" => Some(Counter::Depletion),
            "experience counter" | "experience counters" => Some(Counter::Experience),
            "quest counter" | "quest counters" => Some(Counter::Quest),
            "storage counter" | "storage counters" => Some(Counter::Storage),
            "verse counter" | "verse counters" => Some(Counter::Verse),
            "acorn counter" | "acorn counters" => Some(Counter::Acorn),
            "aim counter" | "aim counters" => Some(Counter::Aim),
            "blaze counter" | "blaze counters" => Some(Counter::Blaze),
            "blood counter" | "blood counters" => Some(Counter::Blood),
            "bounty counter" | "bounty counters" => Some(Counter::Bounty),
            "coin counter" | "coin counters" => Some(Counter::Coin),
            "collection counter" | "collection counters" => Some(Counter::Collection),
            "corpse counter" | "corpse counters" => Some(Counter::Corpse),
            "delay counter" | "delay counters" => Some(Counter::Delay),
            "devotion counter" | "devotion counters" => Some(Counter::Devotion),
            "doom counter" | "doom counters" => Some(Counter::Doom),
            "dream counter" | "dream counters" => Some(Counter::Dream),
            "egg counter" | "egg counters" => Some(Counter::Egg),
            "eon counter" | "eon counters" => Some(Counter::Eon),
            "fate counter" | "fate counters" => Some(Counter::Fate),
            "feather counter" | "feather counters" => Some(Counter::Feather),
            "fetch counter" | "fetch counters" => Some(Counter::Fetch),
            "flame counter" | "flame counters" => Some(Counter::Flame),
            "flood counter" | "flood counters" => Some(Counter::Flood),
            "fungus counter" | "fungus counters" => Some(Counter::Fungus),
            "fuse counter" | "fuse counters" => Some(Counter::Fuse),
            "gold counter" | "gold counters" => Some(Counter::Gold),
            "growth counter" | "growth counters" => Some(Counter::Growth),
            "hatchling counter" | "hatchling counters" => Some(Counter::Hatchling),
            "healing counter" | "healing counters" => Some(Counter::Healing),
            "hit counter" | "hit counters" => Some(Counter::Hit),
            "hour counter" | "hour counters" => Some(Counter::Hour),
            "ice counter" | "ice counters" => Some(Counter::Ice),
            "infection counter" | "infection counters" => Some(Counter::Infection),
            "judgment counter" | "judgment counters" => Some(Counter::Judgment),
            "landmark counter" | "landmark counters" => Some(Counter::Landmark),
            "luck counter" | "luck counters" => Some(Counter::Luck),
            "net counter" | "net counters" => Some(Counter::Net),
            "omen counter" | "omen counters" => Some(Counter::Omen),
            "page counter" | "page counters" => Some(Counter::Page),
            "plague counter" | "plague counters" => Some(Counter::Plague),
            "point counter" | "point counters" => Some(Counter::Point),
            "pressure counter" | "pressure counters" => Some(Counter::Pressure),
            "prey counter" | "prey counters" => Some(Counter::Prey),
            "pupa counter" | "pupa counters" => Some(Counter::Pupa),
            "polyp counter" | "polyp counters" => Some(Counter::Polyp),
            "scream counter" | "scream counters" => Some(Counter::Scream),
            "scroll counter" | "scroll counters" => Some(Counter::Scroll),
            "slime counter" | "slime counters" => Some(Counter::Slime),
            "soul counter" | "soul counters" => Some(Counter::Soul),
            "spark counter" | "spark counters" => Some(Counter::Spark),
            "spite counter" | "spite counters" => Some(Counter::Spite),
            "stash counter" | "stash counters" => Some(Counter::Stash),
            "story counter" | "story counters" => Some(Counter::Story),
            "strife counter" | "strife counters" => Some(Counter::Strife),
            "study counter" | "study counters" => Some(Counter::Study),
            "supply counter" | "supply counters" => Some(Counter::Supply),
            "suspect counter" | "suspect counters" => Some(Counter::Suspect),
            "takeover counter" | "takeover counters" => Some(Counter::Takeover),
            "task counter" | "task counters" => Some(Counter::Task),
            "theft counter" | "theft counters" => Some(Counter::Theft),
            "tide counter" | "tide counters" => Some(Counter::Tide),
            "tower counter" | "tower counters" => Some(Counter::Tower),
            "training counter" | "training counters" => Some(Counter::Training),
            "trap counter" | "trap counters" => Some(Counter::Trap),
            "treasure counter" | "treasure counters" => Some(Counter::Treasure),
            "unity counter" | "unity counters" => Some(Counter::Unity),
            "unlock counter" | "unlock counters" => Some(Counter::Unlock),
            "valor counter" | "valor counters" => Some(Counter::Valor),
            "velocity counter" | "velocity counters" => Some(Counter::Velocity),
            "vow counter" | "vow counters" => Some(Counter::Vow),
            "voyage counter" | "voyage counters" => Some(Counter::Voyage),
            "wage counter" | "wage counters" => Some(Counter::Wage),
            "winch counter" | "winch counters" => Some(Counter::Winch),
            "wind counter" | "wind counters" => Some(Counter::Wind),
            "wish counter" | "wish counters" => Some(Counter::Wish),
            "aegis counter" | "aegis counters" => Some(Counter::Aegis),
            "arrow counter" | "arrow counters" => Some(Counter::Arrow),
            "arrowhead counter" | "arrowhead counters" => Some(Counter::Arrowhead),
            "awakening counter" | "awakening counters" => Some(Counter::Awakening),
            "bait counter" | "bait counters" => Some(Counter::Bait),
            "blessing counter" | "blessing counters" => Some(Counter::Blessing),
            "blight counter" | "blight counters" => Some(Counter::Blight),
            "bloodline counter" | "bloodline counters" => Some(Counter::Bloodline),
            "bloodstain counter" | "bloodstain counters" => Some(Counter::Bloodstain),
            "book counter" | "book counters" => Some(Counter::Book),
            "bore counter" | "bore counters" => Some(Counter::Bore),
            "brain counter" | "brain counters" => Some(Counter::Brain),
            "bribery counter" | "bribery counters" => Some(Counter::Bribery),
            "burden counter" | "burden counters" => Some(Counter::Burden),
            "cage counter" | "cage counters" => Some(Counter::Cage),
            "carrion counter" | "carrion counters" => Some(Counter::Carrion),
            "chip counter" | "chip counters" => Some(Counter::Chip),
            "chorus counter" | "chorus counters" => Some(Counter::Chorus),
            "contested counter" | "contested counters" => Some(Counter::Contested),
            "credit counter" | "credit counters" => Some(Counter::Credit),
            "croak counter" | "croak counters" => Some(Counter::Croak),
            "crystal counter" | "crystal counters" => Some(Counter::Crystal),
            "cube counter" | "cube counters" => Some(Counter::Cube),
            "component counter" | "component counters" => Some(Counter::Component),
            "corruption counter" | "corruption counters" => Some(Counter::Corruption),
            "currency counter" | "currency counters" => Some(Counter::Currency),
            "death counter" | "death counters" => Some(Counter::Death),
            "descent counter" | "descent counters" => Some(Counter::Descent),
            "despair counter" | "despair counters" => Some(Counter::Despair),
            "discovery counter" | "discovery counters" => Some(Counter::Discovery),
            "dread counter" | "dread counters" => Some(Counter::Dread),
            "duty counter" | "duty counters" => Some(Counter::Duty),
            "echo counter" | "echo counters" => Some(Counter::Echo),
            "elixir counter" | "elixir counters" => Some(Counter::Elixir),
            "ember counter" | "ember counters" => Some(Counter::Ember),
            "enlightened counter" | "enlightened counters" => Some(Counter::Enlightened),
            "eruption counter" | "eruption counters" => Some(Counter::Eruption),
            "everything counter" | "everything counters" => Some(Counter::Everything),
            "eyeball counter" | "eyeball counters" => Some(Counter::Eyeball),
            "eyestalk counter" | "eyestalk counters" => Some(Counter::Eyestalk),
            "feeding counter" | "feeding counters" => Some(Counter::Feeding),
            "fellowship counter" | "fellowship counters" => Some(Counter::Fellowship),
            "filibuster counter" | "filibuster counters" => Some(Counter::Filibuster),
            "foreshadow counter" | "foreshadow counters" => Some(Counter::Foreshadow),
            "funk counter" | "funk counters" => Some(Counter::Funk),
            "fury counter" | "fury counters" => Some(Counter::Fury),
            "gem counter" | "gem counters" => Some(Counter::Gem),
            "ghostform counter" | "ghostform counters" => Some(Counter::Ghostform),
            "globe counter" | "globe counters" => Some(Counter::Globe),
            "glyph counter" | "glyph counters" => Some(Counter::Glyph),
            "hack counter" | "hack counters" => Some(Counter::Hack),
            "harmony counter" | "harmony counters" => Some(Counter::Harmony),
            "hatching counter" | "hatching counters" => Some(Counter::Hatching),
            "hone counter" | "hone counters" => Some(Counter::Hone),
            "hoofprint counter" | "hoofprint counters" => Some(Counter::Hoofprint),
            "hope counter" | "hope counters" => Some(Counter::Hope),
            "hourglass counter" | "hourglass counters" => Some(Counter::Hourglass),
            "hunger counter" | "hunger counters" => Some(Counter::Hunger),
            "husk counter" | "husk counters" => Some(Counter::Husk),
            "impostor counter" | "impostor counters" => Some(Counter::Impostor),
            "incarnation counter" | "incarnation counters" => Some(Counter::Incarnation),
            "incubation counter" | "incubation counters" => Some(Counter::Incubation),
            "influence counter" | "influence counters" => Some(Counter::Influence),
            "ingenuity counter" | "ingenuity counters" => Some(Counter::Ingenuity),
            "intel counter" | "intel counters" => Some(Counter::Intel),
            "intervention counter" | "intervention counters" => Some(Counter::Intervention),
            "isolation counter" | "isolation counters" => Some(Counter::Isolation),
            "invitation counter" | "invitation counters" => Some(Counter::Invitation),
            "javelin counter" | "javelin counters" => Some(Counter::Javelin),
            "kick counter" | "kick counters" => Some(Counter::Kick),
            "knickknack counter" | "knickknack counters" => Some(Counter::Knickknack),
            "knowledge counter" | "knowledge counters" => Some(Counter::Knowledge),
            "loot counter" | "loot counters" => Some(Counter::Loot),
            "magnet counter" | "magnet counters" => Some(Counter::Magnet),
            "manifestation counter" | "manifestation counters" => Some(Counter::Manifestation),
            "mannequin counter" | "mannequin counters" => Some(Counter::Mannequin),
            "matrix counter" | "matrix counters" => Some(Counter::Matrix),
            "memory counter" | "memory counters" => Some(Counter::Memory),
            "midway counter" | "midway counters" => Some(Counter::Midway),
            "mine counter" | "mine counters" => Some(Counter::Mine),
            "mining counter" | "mining counters" => Some(Counter::Mining),
            "mire counter" | "mire counters" => Some(Counter::Mire),
            "music counter" | "music counters" => Some(Counter::Music),
            "muster counter" | "muster counters" => Some(Counter::Muster),
            "necrodermis counter" | "necrodermis counters" => Some(Counter::Necrodermis),
            "nest counter" | "nest counters" => Some(Counter::Nest),
            "night counter" | "night counters" => Some(Counter::Night),
            "ore counter" | "ore counters" => Some(Counter::Ore),
            "pain counter" | "pain counters" => Some(Counter::Pain),
            "palliation counter" | "palliation counters" => Some(Counter::Palliation),
            "paralyzation counter" | "paralyzation counters" => Some(Counter::Paralyzation),
            "pause counter" | "pause counters" => Some(Counter::Pause),
            "petal counter" | "petal counters" => Some(Counter::Petal),
            "petrification counter" | "petrification counters" => Some(Counter::Petrification),
            "phyresis counter" | "phyresis counters" => Some(Counter::Phyresis),
            "phylactery counter" | "phylactery counters" => Some(Counter::Phylactery),
            "pin counter" | "pin counters" => Some(Counter::Pin),
            "plot counter" | "plot counters" => Some(Counter::Plot),
            "pop counter" | "pop counters" => Some(Counter::Pop),
            "possession counter" | "possession counters" => Some(Counter::Possession),
            "rejection counter" | "rejection counters" => Some(Counter::Rejection),
            "reprieve counter" | "reprieve counters" => Some(Counter::Reprieve),
            "rev counter" | "rev counters" => Some(Counter::Rev),
            "revival counter" | "revival counters" => Some(Counter::Revival),
            "ribbon counter" | "ribbon counters" => Some(Counter::Ribbon),
            "ritual counter" | "ritual counters" => Some(Counter::Ritual),
            "rope counter" | "rope counters" => Some(Counter::Rope),
            "rust counter" | "rust counters" => Some(Counter::Rust),
            "shell counter" | "shell counters" => Some(Counter::Shell),
            "shoe counter" | "shoe counters" => Some(Counter::Shoe),
            "shred counter" | "shred counters" => Some(Counter::Shred),
            "skewer counter" | "skewer counters" => Some(Counter::Skewer),
            "silver counter" | "silver counters" => Some(Counter::Silver),
            "sleep counter" | "sleep counters" => Some(Counter::Sleep),
            "sleight counter" | "sleight counters" => Some(Counter::Sleight),
            "slumber counter" | "slumber counters" => Some(Counter::Slumber),
            "soot counter" | "soot counters" => Some(Counter::Soot),
            "third-degree-burn counter" | "third-degree-burn counters" => {
                Some(Counter::ThirdDegreeBurn)
            }
            "vitality counter" | "vitality counters" => Some(Counter::Vitality),
            "vortex counter" | "vortex counters" => Some(Counter::Vortex),
            "void counter" | "void counters" => Some(Counter::Void),
            "volatile counter" | "volatile counters" => Some(Counter::Volatile),
            _ => None,
        }
    }
}
